CREATE TABLE PUBLIC.OBJECTLIST
(
OBJECTKEY UUID NOT NULL,
OBJECTTYPE VARCHAR(25) NOT NULL,
CREATED TIMESTAMP NOT NULL,
LASTMODIFIED TIMESTAMP,
LASTSHOWN TIMESTAMP,
DESCRIPTION VARCHAR(2000),
HTMLSRC CLOB,
TEXTCONTENT VARCHAR(64000),
PRIMARY KEY (OBJECTKEY)
);

CREATE TABLE PUBLIC.link
(
LINKKEY UUID NOT NULL,
FROMPK UUID NOT NULL,
TOPK UUID NOT NULL,
VERB VARCHAR(25) DEFAULT 'HTML_LINK',
CREATED TIMESTAMP ,
FLAGS INT NOT NULL DEFAULT 0,
PRIMARY KEY (LINKKEY)
);

CREATE TABLE PUBLIC.TIMELINE
(
CREATED TIMESTAMP NOT NULL,
OBJECTKEY UUID NOT NULL,
ACTION VARCHAR(10) NOT NULL
);

CREATE TABLE PUBLIC.FILEDATA
(
FILEDATAKEY UUID NOT NULL,
MD5 VARCHAR(32) NOT NULL,
MIMETYPE VARCHAR(100)
);

CREATE TABLE PUBLIC.FILEREF
(
OBJECTKEY UUID NOT NULL,
FILENAME VARCHAR(500),
FILEDATAKEY UUID NOT NULL
);

CREATE TABLE PUBLIC.MAIL
(
OBJECTKEY UUID NOT NULL,
messageId VARCHAR(255),
fromaddress VARCHAR(255),
toaddress VARCHAR(255),
cc VARCHAR(255),
bcc VARCHAR(255),
fullheaders VARCHAR(1024)
);