CREATE TABLE PUBLIC.MAILACCOUNTS
(
MAILACCOUNTKEY UUID NOT NULL,
MAILACCOUNTNAME VARCHAR(25) NOT NULL,
MAIL_SERVER VARCHAR(25) NOT NULL,
MAIL_LOGIN VARCHAR(25) NOT NULL,
MAIL_PASS VARCHAR(25) NOT NULL,
MAIL_PROTOCOL VARCHAR(25) NOT NULL,
MAIL_FOLDER VARCHAR(25) NOT NULL,
PRIMARY KEY (MAILACCOUNTKEY)
);