--tabla para el scheduler--
CREATE TABLE PUBLIC.JOBLIST
(
JOBKEY UUID NOT NULL,
JOBNAME VARCHAR(25) NOT NULL,
JOBGROUPNAME VARCHAR(25) NOT NULL,
TRIGGERNAME VARCHAR(25) NOT NULL,
TRIGGERGROUPNAME VARCHAR(25) NOT NULL,
CRONSTRING VARCHAR(25) NOT NULL,
JOBCLASS VARCHAR(25) NOT NULL,
CRONHUMAN VARCHAR(50) NOT NULL,
PRIMARY KEY (JOBKEY)
);

CREATE TABLE PUBLIC.DBINFO
(
DBINFOKEY UUID NOT NULL,
DBINFONAME VARCHAR(25) NOT NULL,
DBINFOVALUE VARCHAR(250) NOT NULL,
PRIMARY KEY (DBINFOKEY)
);


insert into DBINFO values('00000000-0000-0000-0000-000000000001','version','3');

//cosas que hay que corregir
update objectlist  set description = 'BOOKMARK', textcontent ='BOOKMARK' where description ='bookmark';
update objectlist  set description = 'PUBLIC', textcontent ='PUBLIC' where description ='public';

CREATE TABLE PUBLIC.MAILACCOUNTS
(
MAILACCOUNTKEY UUID NOT NULL,
MAILACCOUNTNAME VARCHAR(25) NOT NULL,
MAIL_SERVER VARCHAR(25) NOT NULL,
MAIL_LOGIN VARCHAR(25) NOT NULL,
MAIL_PASS VARCHAR(25) NOT NULL,
MAIL_PROTOCOL VARCHAR(25) NOT NULL,
MAIL_FOLDER VARCHAR(25) NOT NULL,
PRIMARY KEY (MAILACCOUNTKEY)
);